config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home'
  get 'pages/contact'

  # these routes are for showing users a login form, logging them in, and logging them out.
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest
  validates :name, presence: true, length: { maximum: 50 }  
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
 	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }, 
                    uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true



	  # Returns the hash digest of the given string.
  	def self.digest(string)
    	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    	BCrypt::Password.create(string, cost: cost)
  	end

  	# Returns a random token.
  	def self.new_token
    	SecureRandom.urlsafe_base64
  	end

  	# Remembers a user in the database for use in persistent sessions.
	  def remember
    	self.remember_token = User.new_token
    	self.remember_digest = User.digest(self.remember_token)
      #self.update_attribute(:remember_digest, User.digest(self.remember_token))
 	  end

    # Returns true if the given token matches the digest.
    def authenticated?(attribute, token)
      digest = self.send("#{attribute}_digest")
      return false if digest.nil?
      BCrypt::Password.new(digest).is_password?(token)
    end

        # Forgets a user.
    def forget
      self.update_attribute(:remember_digest, nil)
    end

    def activate
      self.update_attribute(:activated,    true)
      self.update_attribute(:activated_at, Time.zone.now)
    end

    # Sends activation email.
    def send_activation_email
      UserMailer.account_activation(self).deliver_now
    end

    # Sets the password reset attributes.
    def create_reset_digest
      self.reset_token = User.new_token
      update_attribute(:reset_digest,  User.digest(reset_token))
      update_attribute(:reset_sent_at, Time.zone.now)
    end

    # Sends password reset email.
    def send_password_reset_email
      UserMailer.password_reset(self).deliver_now
    end

    # Returns true if a password reset has expired.
    def password_reset_expired?
      reset_sent_at < 2.hours.ago
    end
    


  private

        # Converts email to all lower-case.
      def downcase_email
        self.email = email.downcase
      end

      # Creates and assigns the activation token and digest.
      def create_activation_digest
        self.activation_token  = User.new_token
        self.activation_digest = User.digest(self.activation_token)
      end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
	before_action :correct_user, only: [:edit, :update]
	before_action :admin_user,     only: [:destroy]

	def index
		@users = User.all
		@title = "Tous les utilisateurs"
		@users = User.paginate(page: params[:page])
	end


	def show
		@user = User.find(params[:id])
		@title = 'Profil'
	end

	def new
		@user = User.new
		@title = 'Nouveau Profil'
	end

	def create
	  	@user = User.new(user_params)
  		if @user.save
  			@user.send_activation_email
        flash[:info] = "Verifie tes emails pour activer ton compte."
        redirect_to root_url
  		else
    		render :new
  		end
	end

	def edit
    	@user = User.find(params[:id])
    	@title = 'Edition Profil'
  	end

	def update
		@user = User.find(params[:id])
  	   if @user.update_attributes(user_params)
   		    flash[:success] = "Informations mises à jour."
   		    redirect_to user_url     		
  	   else
    		  render 'edit'
  	   end
	end


  #before_filter

   # Confirms the correct user.
  def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
  end

  # Confirms an admin user.
  def admin_user
      redirect_to(root_url) unless current_user.admin?
  end


  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Un péperoner parti trop tôt ..."
    redirect_to root_url
  end


	
	private


  	  def user_params
  		    params.require(:user).permit(:name, :email, :password, :password_confirmation, :pseudo, :last_name, :phone_number)
  	  end



end

app/helpers/users_helper.rb
module UsersHelper
		 # Returns the Gravatar for the given user.
  def gravatar_for(user, size: 150 )
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url =  "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: "peperoni + user.name", class: "gravatar")
  end
end

app/views/users/edit.html.erb
<div class="row edit-user-form">
  <div class="col-md-6 col-md-offset-3">
        <h2>Mettre à jour vos infos personnelles</h2>

    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>


      <%= f.label :Prénom %>
      <%= f.text_field :name.downcase, class: 'form-control' %>

      <%= f.label :Nom %>
      <%= f.text_field :last_name, class: 'form-control' %>      

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :pseudo %>
      <%= f.text_field :pseudo, class: 'form-control' %>

      <%= f.label :phone_number, "Téléphone" %>
      <%= f.phone_field :phone_number, class: 'form-control' %>

      <br>
      <div><center>Pas besoin de réecrire ton mot de passe si tu ne souhaites pas les changer </center></div>      

      <%= f.label :password, "Mot de passe" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation du mot de passe" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <br>
    <center>
      <%= f.submit "Enregistrer", class: "btn btn-primary" %>
    </center>
    <% end %>
    <br>
    <div class="gravatar_edit">
      <center>
        <%= gravatar_for @user %>
        <a href="http://gravatar.com/emails" target="_blank"><br>Modifier</a>
      </center>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<section class="container" id="index-users">
	<div class="row">

		<h1>La Communauté Pépéroner</h1>
		<br>
		<%= will_paginate %>

		<ul class="users">
		  <% @users.each do |user| %>
		   <div class="col-lg-3 col-sm-6 col-md-4 col-xs-12 users-bkg1"> 
			   	
		   		<div class="users-bkg2"
				   	<li>
				      <%= gravatar_for user, size: 130 %>
				      <h2 class="pseudo-index">
				      	<% if user.pseudo.nil? %>
				      	<% elsif user.pseudo == "" %>
				      	<% else %>
				      		<%= "#"+user.pseudo %>			      	
				      	<% end %>
				      </h2>				      
				      <p><%= user.name.capitalize %>
			      	  	<% if current_user.admin? && !current_user?(user) %>
					  	| <%= link_to "X", user, method: :delete, data: { confirm: "Certain ?" } %>
						<% end %>
					  </p>
				    </li>
				</div>
			</div>
		  <% end %>
		</ul>
		<%= will_paginate %>
	</div>	

</section>

app/views/users/new.html.erb
<section id="signup">
	<div class="row" id="formulaire_sign_up">
		<div class="col-md-6 col-md-offset-3">
			<center>
			<h1>Inscris-Toi, Nouveau Pépéroner !</h1>
			</center>
			<br>

	  		<%= form_for :user, url: '/users' do |f| %>
			<%= render 'shared/error_messages' %>

				<%= f.label :name, "Prénom" %>
				<%= f.text_field :name, class: 'form-control' %>

				<%= f.label :email, "Email" %>
				<%= f.text_field :email, class: 'form-control' %>

				<%= f.label :password, "Mot de Passe" %>
				<%= f.password_field :password, class: 'form-control' %>

				<%= f.label :password_confirmation, "Confirmation du Mot de Passe" %>
				<%= f.password_field :password_confirmation, class: 'form-control' %>

				<center><%= f.submit "Créer mon compte", class: "btn btn-primary", id: "button-form-2" %></center>

				<% end %>

			</div>
		</div>
	</section>

app/views/users/show.html.erb
<section class="" id="Espaceperso">

	<div class="row" id="perso-backg">
		<h1>Ton espace à toi</h1>
	</div>

	<div class="container no-gutters" id="spacebox1">
		<div class="title-perso col-md-12">
			<div class="col-md-11"><p>Mes informations personnelles</p></div>
			<div class="col-md-1 link"><%= link_to 'Modifier', edit_user_url(current_user) %> </div>
		</div>

		<div class="col-md-4 container gravatar">
			        <%= gravatar_for @user, size: 120 %>
		</div>
		<div class="col-md-8 container">
			<table id="espacepersoinfos">
				<tr>
					<td class="col-*-3 container">Pseudo:</td>
					<td class="col-*-5 container">
						<% if current_user.pseudo.nil?  %>
						Pas de pseudo
						<% else %>
						<%= current_user.pseudo.capitalize %>
						<% end %>
					</td>
				</tr>
				<tr>
					<td class="col-*-3 container">Prénom :</td>
					<td class="col-*-5 container"><%= current_user.name %></td>
				</tr>
				<tr>
					<td class="col-*-3 container">Nom :</td>
					<td class="col-*-5 container">
						<% if current_user.last_name.nil?  %>
						Pas de nom de famille
						<% else %>
						<%= current_user.last_name %>
						<% end %></td>
				</tr>
				<tr>
					<td class="col-*-3 container">Email :</td>
					<td class="col-*-5 container"><%= current_user.email %></td>
				</tr>
				<tr>
					<td class="col-*-3 container"> Téléphone :</td>
					<td class="col-*-5 container">
						<% if current_user.phone_number.nil?  %>
						Pas de numéro !
						<% else %>
						<%= current_user.phone_number %>
						<% end %>
					</td>
				</tr>
				<tr>
					<td class="col-*-3 container"> Arrivée :</td>
					<td class="col-*-5 container">
						<%= current_user.created_at.strftime("%d/%m/%y") %>
					</td>
				</tr>
			</table>
		</div>
	</div>

</section>