config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home'
  get 'pages/contact'

  # these routes are for showing users a login form, logging them in, and logging them out.
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 	  <title><%= @title %> | Peperoni Cafe</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="/assets/application.js"
            rel="stylesheet"
              type="text/css" data-turbolinks-track>
  	<%= csrf_meta_tag %>
    <meta charset="utf-8">
    <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <meta name="description" content="La vie de moi et les aléas qui se passent dans sa tête.">
</head>
    
<body>

  <header id="header" role="banner" class="main-header">
    <div class="header-inner row">
      <h1 class="col-sm-4"><a id="HPlink" href="/">WELCOME</a></h1>
      <nav class="col-sm-8">
        <div id="login-logout">
          <% if current_user %>
          Bonjour, <%= current_user.name.capitalize %> ! | <%= link_to "X", logout_path %>
          <% else %>
          <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
          <% end %>
        </div>
        <div>
          <% if current_user %>
          <%= link_to "Espace perso", user_path(current_user) %>
          <% else %>
          <% end %>
        </div>
        <a href="/pages/contact"><p>Contact</p></a>
      </nav>
    </div>
  </header>
  <% flash.each do |message_type, message| %>
        <div class="alert jumbotron alert-<%= message_type %>"><p><%= message %></p></div>
      <% end %>

<%= yield %>

  <footer>
    <div class="row">
      <p class="col-sm-4">&copy; Peperoni Cafe Ltd.</p>
      <ul class="col-sm-8">
        <li class="col-sm-1">
          <img src="https://s3.amazonaws.com/codecademy-content/projects/make-a-website/lesson-4/twitter.svg">
        </li>
        <li class="col-sm-1">
          <img src="https://s3.amazonaws.com/codecademy-content/projects/make-a-website/lesson-4/facebook.svg">
        </li>
        <li class="col-sm-1">
          <img src="https://s3.amazonaws.com/codecademy-content/projects/make-a-website/lesson-4/instagram.svg">
        </li>
        <li class="col-sm-1">
          <img src="https://s3.amazonaws.com/codecademy-content/projects/make-a-website/lesson-4/medium.svg">
        </li>
      </ul>
    </div>
  </footer>

</body>
</html>